{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0.jar",
          "url": "junit-jupiter-api-5.9.0.jar",
          "size": 203401,
          "sha512": "53bd60f8212f902289e8ceb3a0f0083bd8c958f17e14b34eff40d6c6fd9aed3c294ac38c9ba052be859d6418869d4ebca1503efc4ac4e66300c1b8a9b43a810c",
          "sha256": "3e370bcbb1e857fda5f0b203724116d02b05e788faa1eb2518814accf9cfb5b1",
          "sha1": "00a44f7eba3ea214f6ec87ad9fccd3b2ac4681a4",
          "md5": "1d7fe5b06c9bee2051163abe833037f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0.jar",
          "url": "junit-jupiter-api-5.9.0.jar",
          "size": 203401,
          "sha512": "53bd60f8212f902289e8ceb3a0f0083bd8c958f17e14b34eff40d6c6fd9aed3c294ac38c9ba052be859d6418869d4ebca1503efc4ac4e66300c1b8a9b43a810c",
          "sha256": "3e370bcbb1e857fda5f0b203724116d02b05e788faa1eb2518814accf9cfb5b1",
          "sha1": "00a44f7eba3ea214f6ec87ad9fccd3b2ac4681a4",
          "md5": "1d7fe5b06c9bee2051163abe833037f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-javadoc.jar",
          "url": "junit-jupiter-api-5.9.0-javadoc.jar",
          "size": 781320,
          "sha512": "a30d43c8c372656a0ecf0a82e9515318c89d02f30c9c97780cb0de9b775f19403f36822bea90a2900136641f0d40e46313d1242c672000f6708d1db6e2ae56fe",
          "sha256": "e04ab1a07b352d4c7f8240f319f077954d4a527f73d61aca7bbf32ab4dcc00f0",
          "sha1": "1830b133f90eb39f59046939b78036ce39760576",
          "md5": "68f864052d58b77222890b48b3dad4c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-sources.jar",
          "url": "junit-jupiter-api-5.9.0-sources.jar",
          "size": 198666,
          "sha512": "3799e6e9a40b8aa8b3f3f085b971d54fee15f465a0d6ab50ecbf5a5bb846bdb1059c7115a7a94fb729e83873cf451facf717d283e73684b0716a2555ddee2630",
          "sha256": "fa61dac36eb90a3bc30e00d77eb033bcf4b1f921be0f637c460b53ee69b8439e",
          "sha1": "0e23e68771c361cdc17004c5ec30095d609df980",
          "md5": "8b52d8e2842f277c441a74c9aac53568"
        }
      ]
    }
  ]
}
