{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-engine",
    "version": "5.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0.jar",
          "url": "junit-jupiter-engine-5.9.0.jar",
          "size": 246427,
          "sha512": "754fe9dbd36f8fc9075e0133deb2e149e94c4526b2930145c79cf9627c4742e09e48060d291c0c5f5831f663a2cdd086b57feb0c7b8f68cd9ff3707b9ed978e1",
          "sha256": "db86cbb3352719fa0a97800edfd09c20463c7f2ab4a04699244430bd8954583b",
          "sha1": "0cc1cb5efae97493dcffb687253a0964ad2e7b99",
          "md5": "fc65ce46d1462fa7e610c07ac27a2dbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0.jar",
          "url": "junit-jupiter-engine-5.9.0.jar",
          "size": 246427,
          "sha512": "754fe9dbd36f8fc9075e0133deb2e149e94c4526b2930145c79cf9627c4742e09e48060d291c0c5f5831f663a2cdd086b57feb0c7b8f68cd9ff3707b9ed978e1",
          "sha256": "db86cbb3352719fa0a97800edfd09c20463c7f2ab4a04699244430bd8954583b",
          "sha1": "0cc1cb5efae97493dcffb687253a0964ad2e7b99",
          "md5": "fc65ce46d1462fa7e610c07ac27a2dbb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-javadoc.jar",
          "url": "junit-jupiter-engine-5.9.0-javadoc.jar",
          "size": 408231,
          "sha512": "7905df5b0bf16470508e7cc9a34344d253d11d5917234f404db2d247ec6d47c298045f3df6802ec3612d93b4b3899307000ba1dc1476609ffda522f7eb8ad93b",
          "sha256": "4cc1a56213d22c50a9155b4995d779e6add9a0047c49a805f336661aa490d77a",
          "sha1": "3411f7b63f24b4cb270aec94a56824873a801623",
          "md5": "60ac9a8219e2b14020ece59440088140"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-sources.jar",
          "url": "junit-jupiter-engine-5.9.0-sources.jar",
          "size": 130699,
          "sha512": "707d8045de583c35e472dbaa84bc62525e239ffa8ff474d6dba077859e6449cc47ab18f6c673933056a7e0ee15505b5f89064d4b4b365f0bce1fa92fd3aa5695",
          "sha256": "9ec3a8efe69155c965a885af66ee7b0f898cb8b41ed6c8703c2f4a3705f9f367",
          "sha1": "1342cdbc880788707e133ec3a8dc9cbf84b041df",
          "md5": "3b6d74d56d2015812046c2ebbbd3b66c"
        }
      ]
    }
  ]
}
